version: '3'
services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "5001:5000"

  service2:
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "5002:5000"

  ambassador:
    build:
      context: .
      dockerfile: Dockerfile-ambassador
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
